repos:
  - repo: local
    hooks:
      - id: autopep8
        name: Formatting
        entry: autopep8 -i
        language: system
        types: [python]
        stages: [commit]
      - id: flake8
        name: Flake8
        additional_dependencies: [flake8-docstrings, flake8-quotes]
        entry: flake8 --show-source
        language: system
        types: [python]
        stages: [commit]
fail_fast: true
