version: "3.5"

services:
  server:
    networks:
      - default
    build:
      context: .
    command: python -m app.server
    restart: always
    environment:
      PYTHON_ENV: development
      APP_PORT: 8100
      APP_HOST: "0.0.0.0"
    container_name: fast-api-server
    ports:
      - "8100:8100"
networks:
  default:
    name: fast-api
